var name="Abisha";
var age=21;
var dob="28/10/2004";
var height=150.5;
var weight=44.5;
var degree="BE CSE";
var gender="Female";
console.log("Name :"+name);
console.log("Age :"+age);
console.log("Date Of Birth :"+dob);
console.log("Height :"+height);
console.log("Weight :"+weight);
console.log("Degree :"+degree);
console.log("Gender :"+gender);
