var a=10;
a++;
console.log("After post-increment :"+a);
++a;
console.log("After pre-increment :"+a);
a--;
console.log("After post-decrement :"+a);
--a;
console.log("After pre-decrement :"+a);
var b=20;
var c=30;
console.log("Equal to :"+(b==c));
console.log("Not equal to :"+(b!=c));
console.log("Strict equal to :"+(b===c));
console.log("Strict not equal to :"+(b!==c));
console.log("Greater than :"+(b>c));
console.log("Less than :"+(b<c));
console.log("Greater than or equal to :"+(b>=c));
console.log("Less than or equal to :"+(b<=c));
